//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriconApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgriconWebApiEntities : DbContext
    {
        public AgriconWebApiEntities()
            : base("name=AgriconWebApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Despesas> Despesas { get; set; }
        public virtual DbSet<PrecoAgricola> PrecoAgricola { get; set; }
        public virtual DbSet<Produtor> Produtor { get; set; }
        public virtual DbSet<Propriedade> Propriedade { get; set; }
        public virtual DbSet<PropriedadeSafra> PropriedadeSafra { get; set; }
        public virtual DbSet<Recepcao> Recepcao { get; set; }
        public virtual DbSet<ResultadoSimulacao> ResultadoSimulacao { get; set; }
        public virtual DbSet<Safra> Safra { get; set; }
    }
}
