//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriconApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropriedadeSafra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropriedadeSafra()
        {
            this.Despesas = new HashSet<Despesas>();
            this.Recepcao = new HashSet<Recepcao>();
            this.ResultadoSimulacao = new HashSet<ResultadoSimulacao>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PropriedadeId { get; set; }
        public Nullable<long> SafraId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despesas> Despesas { get; set; }
        public virtual Propriedade Propriedade { get; set; }
        public virtual Safra Safra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcao> Recepcao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoSimulacao> ResultadoSimulacao { get; set; }
    }
}
